server:
    port: 8050
eureka:
    client:
       serviceUrl:
          defaultZone: http://garyhu:123456@localhost:8761/eureka/
    instance:
       prefer-ip-address: true
spring:
   application:
      name: springcloudfileupload
   http:
      max-file-size: 2000Mb                   # Max file size，默认为1M
      max-request-size: 2500Mb                # Max request size, 默认10M                    