server: 
    port: 8070
spring:
   application:
       name: springcloudzuulsidecar
eureka:
   client:
      service-url:
          defaultZone: http://garyhu:123456@localhost:8761/eureka/
   instance:
      prefer-ip-address: true
# Node.js 的服务存放在D盘，node-service.js 运行服务的代码为： node node-service.js      
sidecar:
   port: 8060                                           # Node.js微服务的端口
   health-url: http://localhost:8060/health.json        # Node.js微服务的健康检查URL                        