server:
   port: 8045
spring:
   application:
      name: springcloudzuulaggregate
eureka:
   client:
      service-url:
          defaultZone: http://garyhu:123456@localhost:8761/eureka/
   instance:
       prefer-ip-address: true
