server:
   port: 8040
spring:
   application:
      name:springcloud6
eureka:
   client:
      service-url:
         defaultZone: http://garyhu:123456@localhost:8761/eureka/         
      instance:
         prefer-ip-address: true   
turbine:
    appConfig:  springcloud2,springcloudstream
    clusterNameExpression: "'default'"        